export const FETCH_LINKS = 'FETCH_LINKS';
export const FETCH_SAVED_LINKS = 'FETCH_SAVED_LINKS';
export const SAVE_LINK = 'SAVE_LINK';
export const FETCH_TOP_SAVED_LINKS = 'FETCH_TOP_SAVED_LINKS';
export const REMOVE_LINK = 'REMOVE_LINK';
export const PREVIEW_LINK = 'PREVIEW_LINK';
